### ISSUE TITLE
broken link in the source code

### ISSUE THREAD

**Issue by ugorek000** [WannesMalfait/Blender-Add-ons#18]
positioning.py 132
```python
class TreePositioner():
      """
      Class to position nodes in a node tree
      Algorithm: https://www.cs.unc.edu/techreports/89-034.pdf
      """
```
Link `https://www.cs.unc.edu/techreports/89-034.pdf` don't work.
![image](https://github.com/WannesMalfait/Blender-Add-ons/assets/120259754/4d489bdc-f87d-48b1-a293-c323fd53caf2)

Here is the actual link:
https://techreports.cs.unc.edu/papers/89-034.pdf

**Comment by WannesMalfait** [comment]
Yep, looks like they changed the link. Thanks for letting me know

**Comment by ugorek000** [comment]
If you are interested, I made my own version of node organization:
https://youtu.be/b_F4dB3Z2LE

**Comment by WannesMalfait** [comment]
Looks good! The resulting layout looks a bit similar to what this add-on does, but it is probably better than what I do. For this add-on the main goal is just to have the nodes be somewhat organized, so that the user can easily layout the nodes how they want afterwards. The node layout being perfect isn't a main goal of this add-on, so changing the positioning algorithm is a low priority
